### PR TITLE
Updated recipes for GStreamer 1.16.0

### PR DESCRIPTION
**Pull request by philn**

### CODE REVIEW

**Comment by otavio** [comment]
Please add your signed-off-by.

**Comment by philn** [comment]
Ping @dv1 ?

**Comment by dv1** [comment]
I'll try to build GStreamer with this, then I can comment.

**Comment by dv1** [comment]
In the commit messages for each .bb recipe please write why you add/remove/modify patches (unless the changes are trivial, like patch line number changes or md5sum hash changes). It is important to keep track of why these changes were made.

**Comment by dv1** [comment]
How did you build this? I have trouble building gstreamer1.0-plugins-base. I get errors like:

    gstreamer1.0-plugins-base/1.16.0-r0/recipe-sysroot/usr/include/gstreamer-1.0/gst/gstcaps.h:242: syntax error, unexpected identifier, expecting ',' or ';' in '  do { G_STATIC_ASSERT (sizeof *(((GstMiniObject **) caps_ptr)) == sizeof (gpointer)); __typeof__((((GstMiniObject **) caps_ptr))) _pp = (((GstMiniObject **) caps_ptr)); __typeof__(*(((GstMiniObject **) caps_ptr))) _ptr = *_pp; *_pp = ' at '_pp'

**Comment by philn** [comment]
It builds fine here in sumo with gcc 7.3.0 and the following tunes `TUNE_FEATURES        = "arm armv7a vfp thumb neon callconvention-hard cortexa9"`

**Comment by dv1** [comment]
@philn Can you try to build with Thud?

**Comment by philn** [comment]
Builds fine with Thud as well :)

**Comment by philn** [comment]
@dv1 PR updated!

**Comment by philn** [comment]
Ah, wait, the libav recipe needs a few more changes

**Comment by philn** [comment]
Ok, I'm done now, please review ;)

**Comment by dv1** [comment]
Working on it. It builds now after reworking the commits. I'll post updated versions in 1-2 days.

**Comment by dv1** [comment]
I reworked the patches and merged them. Thanks!

I had to make some differences to the patches, most notably 0004-rtsp-drop-incorrect-reference-to-gstreamer-sdp-in-Ma.patch, which I had to keep in, and did not see where this was upstreamed. Perhaps in master, but it is not part of 1.16.0.

**Review by dv1 — COMMENTED** [review]
Reworked these patches and merged them to master and warrior branches.

**Pull request closed without merging**
