### PR TITLE
GStreamer 1.14.4 for Sumo branch

### PR DESCRIPTION
**Pull request by philn**

### CODE REVIEW

**Comment by otavio** [comment]
Thank you for working on this.

Please `cherry-pick` each of `master` commits and drop the `conf/layer.conf` changes as they are non-related.

**Comment by philn** [comment]
Well, https://github.com/OSSystems/meta-gstreamer1.0/pull/22/commits/6df5275e9cace1959914ef02022d33271c10ef49 is needed :)

**Comment by otavio** [comment]
> Well, [6df5275](https://github.com/OSSystems/meta-gstreamer1.0/commit/6df5275e9cace1959914ef02022d33271c10ef49) is needed :)

Not really. It is because you are merging `master` onto `sumo` and it brings https://github.com/OSSystems/meta-gstreamer1.0/pull/22/commits/1d20941a32f71ab25c2032cb7d5063f522290a99 in.

That's why I said `cherry-pick` (especially using -x command line argument so it is clear it is importing a commit) ;-)

**Comment by philn** [comment]
I don't see what's the difference. If you want to update the sumo branch yourself from master, please go ahead and close this PR.

**Comment by otavio** [comment]
We keep history clean. This is a backport so please reconsider and update this PR so we can merge it.

Doing the `cherry-pick -x` allow for easy trace of what is being backported and what is made for a branch.

**Comment by philn** [comment]
Done!

**Comment by philn** [comment]
Done!

**Pull request merged**
