### PR TITLE
dunfell: sync with oe-core

### PR DESCRIPTION
**Pull request by quaresmajose**

### CODE REVIEW

**Comment by otavio** [comment]
How this was tested?

**Comment by quaresmajose** [comment]
This is tested in oe-core master on the autobuilder, my propose is only to have dunfell synced with master.
The recipes-graphics is needed to build the vulkan plugin in gstreamer-plugin-bad-1.18.
```
git diff --stat master dunfell 
 conf/layer.conf                                                                            |   2 +-
 recipes-graphics/glslang/glslang/0001-generate-glslang-pkg-config.patch                    |  47 ++++++++++++++++++++++
 recipes-graphics/glslang/glslang_11.4.0.bb                                                 |  31 +++++++++++++++
 recipes-graphics/shaderc/files/0001-cmake-disable-building-external-dependencies.patch     | 109 ++++++++++++++++++++++++++++++++++++++++++++++++++++
 recipes-graphics/shaderc/files/0002-libshaderc_util-fix-glslang-header-file-location.patch |  28 ++++++++++++++
 recipes-graphics/shaderc/shaderc_2020.5.bb                                                 |  28 ++++++++++++++
 recipes-graphics/spir/files/0001-fix-strncpy-bound-error.patch                             |  30 +++++++++++++++
 recipes-graphics/spir/spirv-headers_1.5.4.bb                                               |  18 +++++++++
 recipes-graphics/spir/spirv-tools_2020.7.bb                                                |  42 ++++++++++++++++++++
 9 files changed, 334 insertions(+), 1 deletion(-)
```

**Comment by otavio** [comment]
We need it to be tested with dunfell prior merge. Could you try that?

**Comment by otavio** [comment]
If this isn't going to be tested, we'll close this PR.

**Comment by quaresmajose** [comment]
I can test it on a qemu but I don't know when and can't even promise anything, so you can close the PR.
Chose what is better for you.
If there are someone that can test it feel free to do it.

**Comment by otavio** [comment]
I don't want to merge an untested PR so will wait few more days and close otherwise.

**Comment by quaresmajose** [comment]
I have run the ptest on qemu and one of the tests is failing.

**poky + meta-gstreamer**
```
root@qemux86-64:~# cat /etc/build 
-----------------------
Build Configuration:  |
-----------------------
DISTRO = poky
DISTRO_VERSION = 3.1.7
-----------------------
Layer Revisions:      |
-----------------------
gstreamer         = dunfell:1f771aacb3019db1ede1d1f6226a98eb1503b185 
meta              = dunfell:e7a5814b4b74d60a21480f7f386a38d3080f1fc2 
meta-poky         = dunfell:e7a5814b4b74d60a21480f7f386a38d3080f1fc2 
meta-yocto-bsp    = dunfell:e7a5814b4b74d60a21480f7f386a38d3080f1fc2 
```
**ptest-runner summary**
```
SUMMARY: total=103; passed=102; skipped=0; failed=1; user=20.7s; system=4.5s; maxrss=9848
FAIL: gstreamer/elements_dataurisrc.test (Child process exited with code 1)

ERROR: Exit status is 512
DURATION: 84
END: /usr/lib/gstreamer1.0/ptest
2021-05-22T14:59
STOP: ptest-runner
```
**the failing test**
```
Running test: gstreamer/elements_dataurisrc.test
+ source /usr/libexec/installed-tests/gstreamer/elements_dataurisrc.env
+ CK_DEFAULT_TIMEOUT=20
+ GST_PLUGIN_LOADING_WHITELIST=gstreamer
+ GST_REGISTRY=/home/root/.cache/gstreamer-1.0/elements_dataurisrc.registry
+ GST_STATE_IGNORE_ELEMENTS=
+ exec /usr/libexec/installed-tests/gstreamer/elements_dataurisrc
Running suite(s): dataurisrc


Unexpected critical/warning: gst_memory_new_wrapped: assertion 'data != NULL' failed

Stack trace:
/usr/lib/libgstreamer-1.0.so.0(+0x7353c) [0x7fd863ccf53c]
/usr/lib/libgstcheck-1.0.so.0(+0xab2b) [0x7fd863c42b2b]
/usr/lib/libglib-2.0.so.0(g_logv+0x214) [0x7fd863b0de14]
/usr/lib/libglib-2.0.so.0(g_log+0x8f) [0x7fd863b0dfff]
/usr/lib/libgstreamer-1.0.so.0(gst_memory_new_wrapped+0xdd) [0x7fd863c9ab9d]
/usr/lib/libgstreamer-1.0.so.0(gst_buffer_new_wrapped_full+0x4b) [0x7fd863ca53ab]
/usr/lib/libgstreamer-1.0.so.0(gst_buffer_new_wrapped+0x1f) [0x7fd863ca551f]
/usr/lib/gstreamer-1.0/libgstcoreelements.so(+0x10aec) [0x7fd8636a4aec]
/usr/lib/libgobject-2.0.so.0(g_object_set_valist+0x3a6) [0x7fd863bf7f16]
/usr/lib/libgobject-2.0.so.0(g_object_set+0xec) [0x7fd863bf87fc]
/usr/libexec/installed-tests/gstreamer/elements_dataurisrc(+0x477e) [0x561c75f4f77e]
/usr/lib/libgstcheck-1.0.so.0(srunner_run_tagged+0x4cd) [0x7fd863c4fced]
/usr/lib/libgstcheck-1.0.so.0(gst_check_run_suite+0x5f) [0x7fd863c43f9f]
/usr/libexec/installed-tests/gstreamer/elements_dataurisrc(+0x2529) [0x561c75f4d529]
/lib/libc.so.6(__libc_start_main+0xeb) [0x7fd863921d0b]
/usr/libexec/installed-tests/gstreamer/elements_dataurisrc(_start+0x2a) [0x561c75f4d56a]

80%: Checks: 5, Failures: 1, Errors: 0
../gstreamer-1.18.4/libs/gst/check/gstcheck.c:286:F:general:test_dataurisrc_uris:0: Unexpected critical/warning: gst_memory_new_wrapped: assertion 'datd
Check suite dataurisrc ran in 0.013s (tests failed: 1)
FAIL: gstreamer/elements_dataurisrc.test (Child process exited with code 1)
```

**Comment by arielmol** [comment]
I can test targeting x86 and Raspberry, how do I test it?

**Comment by arielmol** [comment]
Well I tested it but it seems there is an error:

```bash
| C++ linker for the host machine: x86_64-poky-linux-g++ -m64 -march=nehalem -mtune=generic -mfpmath=sse -msse4.2 -fstack-protector-strong -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security --sysroot=/home/ariel/projects/poky/apollo/tmp/work/corei7-64-poky-linux/gstreamer1.0-plugins-good/1.18.4-r0/recipe-sysroot ld.bfd 2.34.0.20200220
| WARNING: rcc dependencies will not work reliably until this upstream issue is fixed: https://bugreports.qt.io/browse/QTBUG-45460
| Run-time dependency qt5 (modules: Core, Gui, Qml, Quick) found: YES 5.15.0 (pkg-config)
| 
| ext/qt/meson.build:69:7: ERROR: Unknown variable "cxx".
| 
| A full log can be found at /home/ariel/projects/poky/apollo/tmp/work/corei7-64-poky-linux/gstreamer1.0-plugins-good/1.18.4-r0/build/meson-logs/meson-log.txt
| ERROR: meson failed
| WARNING: exit code 1 from a shell command.
| ERROR: Execution of '/home/ariel/projects/poky/apollo/tmp/work/corei7-64-poky-linux/gstreamer1.0-plugins-good/1.18.4-r0/temp/run.do_configure.318660' failed with exit code 1
```
Im not really sure if it is related to this patch, as i get the same error on the dunfell branch of 1.16 here

**Comment by otavio** [comment]
Check without `meta-qt5` layer to confirm it is Qt related.

**Comment by arielmol** [comment]
By removing:  `PACKAGECONFIG_append_pn-gstreamer1.0-plugins-good = " qt5 "` from `local.conf`, it builds okay. Then I put it back and tried without `meta-qt` :
```
NOTE: Resolving any missing task queue dependencies
ERROR: Nothing PROVIDES 'qtbase' (but /home/ariel/projects/poky/meta-gstreamer1.0/recipes-multimedia/gstreamer/gstreamer1.0-plugins-good_1.18.4.bb DEPENDS on or otherwise requires it). Close matches:
  netbase
ERROR: Required build target 'gstreamer1.0-plugins-good' has no buildable providers.
Missing or unbuildable dependency chain was: ['gstreamer1.0-plugins-good', 'qtbase']
```
naturally, it fails as there is no `qtbase` to fulfill the requirement.

**Comment by otavio** [comment]
@dv1 what your view on this?

**Comment by arielmol** [comment]
Anything I can do? I find the warning misterious because that bug was fixed long before Qt 5.15.

**Comment by otavio** [comment]
@desert someone need to step up and prepare a proper PR (tested).

**Comment by arielmol** [comment]
@quaresmajose I tested it by directly cloning your repo, do you have any hint? in order to build it?

**Comment by arielmol** [comment]
By inspecting 1.16x. I have traced this to [this single line in `meson.build`](https://github.com/freedesktop/gstreamer-gst-plugins-good/blob/954af37bc9a31db13e7b2206c3a976177cf6c7b4/meson.build#L20) 
```meson
# FIXME: automagic
have_cxx = add_languages('cpp', required : false)
```
Which in turn makes it believe C++ was detected, then on `ext/qt/meson.build`, [this line](https://github.com/freedesktop/gstreamer-gst-plugins-good/blob/954af37bc9a31db13e7b2206c3a976177cf6c7b4/ext/qt/meson.build#L18) 
```
# FIXME: -Dqt5=enabled is silently ignored if a c++ compiler is not found
if have_cxx and build_gstgl
```
They clearly have `FIXME` comments. Somehow C++ is being misdetected and we get the error. Should we add a DEPEND in order to pass this error? Which one?

**Comment by otavio** [comment]
Superceeded by #60. Closing.

**Pull request closed without merging**
